udp_client:
	gcc -o udp_client.out udp_client.c
	./udp_client.out

udp_server:
	gcc -o udp_server.out udp_server.c
	./udp_server.out

ftp_client:
	gcc -o ftp_client.out ftp_client.c
	./ftp_client.out

ftp_server:
	gcc -o ftp_server.out ftp_server.c
	./ftp_server.out